/*
 * This file is generated by jOOQ.
 */
package jooqexample.infrastructure.jooq.tables.records;


import jooqexample.infrastructure.jooq.tables.Bids;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BidsRecord extends UpdatableRecordImpl<BidsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bids.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bids.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bids.bid</code>.
     */
    public void setBid(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>bids.bid</code>.
     */
    public Double getBid() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>bids.auction_id</code>.
     */
    public void setAuctionId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bids.auction_id</code>.
     */
    public String getAuctionId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bids.bidder_id</code>.
     */
    public void setBidderId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bids.bidder_id</code>.
     */
    public String getBidderId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bids.time_of_bid</code>.
     */
    public void setTimeOfBid(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>bids.time_of_bid</code>.
     */
    public LocalDateTime getTimeOfBid() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BidsRecord
     */
    public BidsRecord() {
        super(Bids.BIDS);
    }

    /**
     * Create a detached, initialised BidsRecord
     */
    public BidsRecord(String id, Double bid, String auctionId, String bidderId, LocalDateTime timeOfBid) {
        super(Bids.BIDS);

        setId(id);
        setBid(bid);
        setAuctionId(auctionId);
        setBidderId(bidderId);
        setTimeOfBid(timeOfBid);
        resetChangedOnNotNull();
    }
}
