/*
 * This file is generated by jOOQ.
 */
package jooqexample.infrastructure.jooq.tables;


import jooqexample.infrastructure.jooq.DefaultSchema;
import jooqexample.infrastructure.jooq.Keys;
import jooqexample.infrastructure.jooq.tables.records.AuctionsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auctions extends TableImpl<AuctionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auctions</code>
     */
    public static final Auctions AUCTIONS = new Auctions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuctionsRecord> getRecordType() {
        return AuctionsRecord.class;
    }

    /**
     * The column <code>auctions.id</code>.
     */
    public final TableField<AuctionsRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auctions.auction_ends</code>.
     */
    public final TableField<AuctionsRecord, LocalDateTime> AUCTION_ENDS = createField(DSL.name("auction_ends"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>auctions.bidder_member_id</code>.
     */
    public final TableField<AuctionsRecord, String> BIDDER_MEMBER_ID = createField(DSL.name("bidder_member_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auctions.bid</code>.
     */
    public final TableField<AuctionsRecord, Double> BID = createField(DSL.name("bid"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>auctions.current_price</code>.
     */
    public final TableField<AuctionsRecord, Double> CURRENT_PRICE = createField(DSL.name("current_price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>auctions.maximum_bid</code>.
     */
    public final TableField<AuctionsRecord, Double> MAXIMUM_BID = createField(DSL.name("maximum_bid"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>auctions.time_of_bid</code>.
     */
    public final TableField<AuctionsRecord, LocalDateTime> TIME_OF_BID = createField(DSL.name("time_of_bid"), SQLDataType.LOCALDATETIME(6), this, "");

    private Auctions(Name alias, Table<AuctionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Auctions(Name alias, Table<AuctionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>auctions</code> table reference
     */
    public Auctions(String alias) {
        this(DSL.name(alias), AUCTIONS);
    }

    /**
     * Create an aliased <code>auctions</code> table reference
     */
    public Auctions(Name alias) {
        this(alias, AUCTIONS);
    }

    /**
     * Create a <code>auctions</code> table reference
     */
    public Auctions() {
        this(DSL.name("auctions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AuctionsRecord> getPrimaryKey() {
        return Keys.AUCTIONS__PK_AUCTIONS;
    }

    @Override
    public Auctions as(String alias) {
        return new Auctions(DSL.name(alias), this);
    }

    @Override
    public Auctions as(Name alias) {
        return new Auctions(alias, this);
    }

    @Override
    public Auctions as(Table<?> alias) {
        return new Auctions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(String name) {
        return new Auctions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(Name name) {
        return new Auctions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(Table<?> name) {
        return new Auctions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Condition condition) {
        return new Auctions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
