# tag::header[]
version: '3'
services:
# end::header[]
  # tag::ravendb[]
  ravendb:
    image: ravendb/ravendb:6.0.1-ubuntu.22.04-x64
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
  # end::ravendb[]
  # tag::eventstoredb[]
  eventstoredb:
    image: 'eventstore/eventstore:21.10.10-bionic'
    ports:
      - 1113:1113
      - 2113:2113
    command: [ '--insecure', '--run-projections=All', '--enable-atom-pub-over-http' ]
  # end::eventstoredb[]
