/*
 * This file is generated by jOOQ.
 */
package jooqexample.infrastructure.jooq;


import jooqexample.infrastructure.jooq.tables.Auctions;
import jooqexample.infrastructure.jooq.tables.Bids;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>auctions</code>.
     */
    public final Auctions AUCTIONS = Auctions.AUCTIONS;

    /**
     * The table <code>bids</code>.
     */
    public final Bids BIDS = Bids.BIDS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Auctions.AUCTIONS,
            Bids.BIDS
        );
    }
}
