/*
 * This file is generated by jOOQ.
 */
package jooqexample.infrastructure.jooq;


import jooqexample.infrastructure.jooq.tables.Auctions;
import jooqexample.infrastructure.jooq.tables.Bids;
import jooqexample.infrastructure.jooq.tables.records.AuctionsRecord;
import jooqexample.infrastructure.jooq.tables.records.BidsRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuctionsRecord> AUCTIONS__PK_AUCTIONS = Internal.createUniqueKey(Auctions.AUCTIONS, DSL.name("pk_auctions"), new TableField[] { Auctions.AUCTIONS.ID }, true);
    public static final UniqueKey<BidsRecord> BIDS__PK_BIDS = Internal.createUniqueKey(Bids.BIDS, DSL.name("pk_bids"), new TableField[] { Bids.BIDS.ID }, true);
}
