/*
 * This file is generated by jOOQ.
 */
package jooqexample.infrastructure.jooq;


import jooqexample.infrastructure.jooq.tables.Auctions;
import jooqexample.infrastructure.jooq.tables.Bids;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>auctions</code>.
     */
    public static final Auctions AUCTIONS = Auctions.AUCTIONS;

    /**
     * The table <code>bids</code>.
     */
    public static final Bids BIDS = Bids.BIDS;
}
